name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t express-app .
      
      - name: Test (Optional)
        run: echo "Run tests here"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST https://api.render.com/deploy/srv-d18dcfqdbo4c739kn23g
